### ISSUE TITLE
Current version not availanle in F-Droid store

### ISSUE THREAD

**Issue by Krawei** [kevinhinterlong/archwiki-viewer#50]
Dear team,

when I take a look in the play store the current version is 1.0.11, in tbe F-Droid store the current version is 1.0.12. What's the reason for this gap? Is there a bug in thr build process? 

Please fix this.

Kind Regards,

Krawei

**Comment by kevinhinterlong** [comment]
Hey!

I'm not really sure what happened with the difference in builds. F-Droid should update based on the git [tags](https://github.com/jtmcn/archwiki-viewer/tags), but for some reason it didn't catch this one. It's hard to tell if this will happen again without making a new release.

I'm not going to push a small release just to test this (since this change was already pretty small), but I'll keep your issue up to be resolved on the next release. If you'd like the newest version without getting it from the Play Store, feel free to check it out from the [releases page](https://github.com/jtmcn/archwiki-viewer/releases/tag/v1.0.12). 

Thank you for pointing this out though

**Comment by rffontenelle** [comment]
[F-Droid appstore currently provides version 1.0.13](https://f-droid.org/pt_BR/packages/com.jtmcn.archwiki.viewer/), so I guess this issue could be closed...?

**Comment by kevinhinterlong** [comment]
Yup it looks like it was just a problem with that version as the git tags are now deploying to F-droid properly
