### ISSUE TITLE
Crashes when trying to share link

### ISSUE THREAD

**Issue by rffontenelle** [kevinhinterlong/archwiki-viewer#72]
I have:
- [X] searched open and closed issues for duplicates
- [X] provided a reproducible result if applicable

----------------------------------------

### Bug description
When trying to share link of the current wiki page, the app crashes. No info provided, just a dialog telling that ArchWiki Viewer stopped and to close it.

### Steps to reproduce 
- Go to the any page in ArchWiki
- Tap on the &vellip; (vertical ellipsis) menu button
- Tap "Share link" menu item (or "Compartilhar link" in my pt_BR translated interface)

**Actual result:** app crashes
**Expected result:** open dialog to select how I want to share the link for that wiki page

### Device info

**Device:** Samsung Galaxy A5 (2017), SM-A520F
**Android version:** 8.0.0
**App version:** 1.0.13
**Language:** Portuguese (Brazil)

**Comment by kevinhinterlong** [comment]
This was fixed in #65 but didn't end up included in the release I made which got deployed as a beta for the Google Play Store and a normal release for F-Droid. It should be resolved in the [v1.0.14 release](https://github.com/kevinhinterlong/archwiki-viewer/releases/tag/v1.0.14) if you want to download the apk directly
